channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pandas
  - pip:
    - requests
    - request_cache
    - multiprocessing
    - numpy
    - plotly
    - jupyter
    - scipy
    - networkx
    - pyMolNetEnhancer
    - loguru