channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8.8
  - pandas
  - numpy
  - plotly
  - jupyter
  - jupyterlab
  - scipy
  - matplotlib
  - scikit-learnç
  - networkx
  - gensim
  - pip>=23.1.2
  - pip:
    - requests
    - seaborn
    - tqdm
    - ipywidgets
    - pyMolNetEnhancer
    - loguru
    - mass-spec-utils
    - redis>=4.6.0
