channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10.6
  - pandas
  - numpy
  - pip>=23.1.2
  - pip:
    - plotly
    - jupyter
    - jupyterlab
    - scipy
    - matplotlib
    - scikit-learn
    - networkx
    - gensim
    - requests
    - requests_cache
    - seaborn
    - tqdm
    - ipywidgets
    - pyMolNetEnhancer
    - loguru
    - mass-spec-utils
    - redis>=4.6.0
